services:
    alg.liveSearch.listener:
        class: alg\liveSearch\event\listener
        arguments:
            - @config
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @auth
        tags:
            - { name: event.listener }
    alg.liveSearch.live_search_ajax_handler:
        class: alg\liveSearch\controller\live_search_ajax_handler
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache
            - %core.root_path%
            - %core.php_ext%
            - @request
            - %core.table_prefix%
            - @service_container
            - @pagination
            - @content.visibility
            - %core.table_prefix%
            - @profilefields.manager
            - @dispatcher
